### ISSUE TITLE
NPC cars have flight enabled on collision

### ISSUE THREAD

**Issue by oOXenonTitareOo** [jackhumbert/let_there_be_flight#13]
AI cars on the road randomly enable flight mode for themselves, wreaking havock and chaos.

**Comment by jackhumbert** [comment]
This is intentional as a test haha. It'll be disabled/available as an option later on.

**Comment by DarthKyp** [comment]
This leads to massive Problems for me. Once a Car is damaged it turns on flight and also panics. Wich leads to huge massive chaos and then usually to a crash.
Same goes for destroyed cars, wich usually crash the game since I installed the mod. Like the massive shootout with the Basilisk Tank completly breaks with this mod.
Also the Place between NC and the Badlands, (the small Bus Stop from the Eurodyne Mission) leads the game to crash everytime, because there is a roadblock of some wraiths nearby, that has a lot of burning cars.

Is there a way to turn this option off now? This is the most fun Mod I ever had in this game, yet it completly kills the playibility with this Mode.

**Comment by jackhumbert** [comment]
Disabled in [v0.0.10](https://github.com/jackhumbert/let_there_be_flight/tree/v0.0.10) :)
